# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: list files
      run: ls -a
      
    - name: Upload .dacpac for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: dacpac
        path: ./Implementation/Data/RegistryDatabase/bin/Debug/netstandard2.0/RegistryDatabase.dacpac

  deploy: 
    needs: build
    runs-on: ubuntu-latest

    steps:                
      - name: download dacpac
        uses: actions/download-artifact@v3.0.2
        with:
          name: dacpac

      - name: Azure SQL Deploy
        uses: Azure/sql-action@v2.1
        with:
          connection-string: '${{ secrets.CONNECTION_STRING }}'
          path: './RegistryDatabase.dacpac'
          action: publish
          arguments: '/p:DropObjectsNotInSource=true'
